### ISSUE TITLE
[PE-D][Tester B] Improvement on the warning message returned

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T17-4/tp#174]
Command that I input: add /nMary p/11111 c/1111 t/1233

Response: Invalid command format! 
add: Adds a person to the address book. Parameters: n/NAME p/PHONE [e/EMAIL] [a/ADDRESS] [th/TELEHANDLE] [t/TAG]... [c/COURSE]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 th/@Johnnnnyyy t/Friend c/CS2100 c/CS2103T c/IS1108

Perhaps try to specify which type of input the user input in an invalid format would be more useful. Currently, I am not sure about whether the input type of phone, course or tag is wrong in the case provided above.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: NgChunMan/ped#1

**Comment by Carlintyj** [comment]
Note taken on feature suggestion.
