### ISSUE TITLE
[PE-D][Tester B] Invalid input for findcourse command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-4/tp#180]
Input command: findcourse cs2103

Respond: output student enrolled in cs2103t.

Perhaps can try to be more specify for the course tag as cs2103 and cs2103t could be two different courses although the name is quite similar. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: NgChunMan/ped#2

**Comment by Carlintyj** [comment]
This is a feature that is expected as stated in the UG. It is part of partial searching.
