### ISSUE TITLE
[PE-D][Tester D] UG Before and After

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T17-4/tp#184]
Perhaps have the before and after images in the UG to be side by side instead of top to bottom? This will let the reader compare between the two states easily, instead of having to continuously scroll up and down.

But otherwise, good visuals!

![Screenshot 2023-11-03 at 4.35.04 PM.png](https://raw.githubusercontent.com/jianrong7/ped/main/files/b0b8fbff-3a40-4589-9f5a-3128002d7f69.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jianrong7/ped#3

**Comment by Carlintyj** [comment]
We tried having the images side by side but the images were too small due to the site template. Thank you!
