### ISSUE TITLE
[PE-D][Tester E] The instruction format in the UG is ambiguous

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T17-4/tp#185]
![Screenshot 2023-11-03 at 4.36.26 PM.png](https://raw.githubusercontent.com/lynnlow175/ped/main/files/30f18a1b-9897-4cf6-ae8b-e8db61d873e0.png)

In the examples, it shows that the format is either one keyword, or several keywords. However, the format is one keyword beside an array of keywords which might confuse the user a little. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: lynnlow175/ped#4

**Comment by Carlintyj** [comment]
The square brackets just like in every other part of the UG represents an optional field not an array. Dont see this as a bug but a misinterpretation from the tester. 

At the minimum, the findstudent command must have at least 1 keyword. If the user chooses to add in more keywords they are allowed to do so but it is optional to them.
