### ISSUE TITLE
[PE-D][Tester A] Unable to view scroll bar for sections on the right side after the application width is reduced

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T17-4/tp#196]
I am still able to scroll with my mouse but it would be better if the width of the sections on the right were reduced when the application width is reduced.

![image.png](https://raw.githubusercontent.com/Goh-Li-Ting/ped/main/files/0bad1ca1-b3d5-4729-b4ab-f4c26929a668.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Goh-Li-Ting/ped#9

**Comment by Carlintyj** [comment]
Will change minimum width and default user preference.
