### ISSUE TITLE
sort name has a bug

### ISSUE THREAD

**Issue by joel-foo** [AY2324S1-CS2103T-T17-4/tp#247]
After performing `sort name` (ascending):
<img width="624" alt="Screenshot 2023-11-08 at 7 58 46 PM" src="https://github.com/AY2324S1-CS2103T-T17-4/tp/assets/76934561/15283da7-b90b-4928-bb6d-e6fc0a8cd06e">

After performing `sort name` (descending):
<img width="585" alt="Screenshot 2023-11-08 at 7 59 21 PM" src="https://github.com/AY2324S1-CS2103T-T17-4/tp/assets/76934561/eb03d243-fdcd-4b1a-b4ec-45700827c06b">

The descending result is incorrect, as the JOHn Cena should appear first, and so on. (To get the descending result, act can just reverse the result of ascending).

**Comment by chewjh1234** [comment]
Thank you @joel-foo for the nice catch!

Indeed, this is a bug that is rather critical. 

Previously, I converted names to uppercase for the sorting. As a result, lowercase and uppercase names were not sorted correctly. It also was not my intention to sort names that way. 

I am currently working on this. Once again, thank you!
